apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    env: visuals
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    env: visuals
spec:
  replicas: 1
  selector:
    matchLabels:
        env: visuals
  template:
    metadata:
      name: grafana-pod
      labels:
         env: visuals
    spec:
      containers:
      - image: 21017/grafana:v1
        name: grafana-container
        ports:
        - containerPort: 3000
          name: grafana-port
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-volume
      volumes:
      - name: grafana-volume
        persistentVolumeClaim:
           claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    env: visuals
  name: grafana-deploy
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    env: visuals
  type: NodePort
status:
  loadBalancer: {}